import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Provider from '@/providers/Provider';
import FullPageLoading from '@/components/Loading/Loading';
import { ToastContainer } from 'react-toastify';
import LayoutWrapper from '@/layouts/LayoutWrapper';

export const metadata: Metadata = {
     title: 'Create Next App',
     description: 'Generated by create next app',
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <html suppressHydrationWarning>
               <body>
                    <Provider>
                         <FullPageLoading />
                         <ToastContainer />
                         <LayoutWrapper>{children}</LayoutWrapper>
                    </Provider>
               </body>
          </html>
     );
}
