import type { Metadata } from 'next';
import './globals.css';
import Provider from '@/providers/Provider';
import FullPageLoading from '@/components/Loading/Loading';
import { ToastContainer } from 'react-toastify';
import LayoutWrapper from '@/layouts/LayoutWrapper';
import '@ant-design/v5-patch-for-react-19';

export const metadata: Metadata = {
     title: 'Employee KWAI',
     description: 'Generated by create next app',
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <html suppressHydrationWarning>
               <body>
                    <Provider>
                         <FullPageLoading />
                         <ToastContainer />
                         <LayoutWrapper>{children}</LayoutWrapper>
                    </Provider>
               </body>
          </html>
     );
}
